### ISSUE TITLE
混淆之后的问题

### ISSUE THREAD

**Issue by bill556** [AleynP/net-cache#1]
混淆之后会抛出异常~
Caused by: java.lang.IllegalArgumentException: Please use okhttp 4.0.0 or later

**Comment by aleyn97** [comment]
@bill556 这个是因为 OKHttp 里的 `DiskLruCache`类被混淆后，构造函数被移除了，创建的时候反射就找不到构造函数。你在`proguard-rules.pro` 文件里加一下这句：
```
 -keepclassmembers class okhttp3.internal.cache.DiskLruCache{
       <init>(***,***,***,***,***,***);
 }
```
保留 DiskLruCache 的构造函数不被混淆就可以了。我下个版本会直接放在 `consumer-rules.pro` 文件里，就不用再手动加了
